INSERT INTO `typebank` (`id_TB`, `nom`, `created_at`, `updated_at`) VALUES
(1, 'ATTIJARIWAFA BANK', NULL, NULL),
(2, 'BANQUE POPULAIRE', NULL, NULL),
(3, 'CIH BANK', NULL, NULL),
(4, 'BMCE BANK', NULL, NULL),
(5, 'BARID BANK', NULL, NULL),
(6, 'CREDIT AGRICOLE', NULL, NULL),
(7, 'CREDIT DU MAROC', NULL, NULL),
(8, 'BANK AL YOUSR', NULL, NULL),
(9, 'UMNIA BANK', NULL, NULL),
(10, 'SOCIETE GENERALE', NULL, NULL);
